apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-admin
  labels: {{- include "common.labels.admin" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "common.labels.admin" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.admin" . | nindent 8 }}
    spec:
      containers:
      - name: graxon-admin
        image: localhost:5001/admin:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8820
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Values.profile }}
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
      serviceAccountName: {{ .Release.Name }}-admin