apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-admin
  namespace: {{ .Release.Namespace }}
  labels: {{- include "admin.labels.default" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "admin.labels.selector" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "admin.labels.selector" . | nindent 8 }}
    spec:
      containers:
        - name: graxon-admin
          image: localhost:5001/admin:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8820
          env:
            {{ include "env.profiles" . | nindent 12 }}
            {{ include "env.actuator" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
      serviceAccountName: {{ .Release.Name }}-admin