apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-admin
  labels: {{- include "common.labels.admin" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  tls:
    - hosts:
        - "admin.{{ .Values.ingress.hostname }}"
      secretName: "admin.{{ .Values.ingress.hostname }}"
  rules:
    - host: "admin.{{ .Values.ingress.hostname }}"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-admin
                port:
                  number: 8820