apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-admin
  namespace: {{ .Release.Namespace }}
  labels: {{- include "admin.labels.default" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-admin
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ .Release.Name }}-admin
    namespace: {{ .Release.Namespace }}