apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin
  namespace: {{ .Release.Namespace }}
  labels: {{- include "admin.labels.default" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8820
      targetPort: http
  selector: {{- include "admin.labels.selector" . | nindent 4 }}