apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-graxon-node
  labels: {{- include "common.labels.node" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "common.labels.node" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.node" . | nindent 8 }}
    spec:
      containers:
        - name: graxon-node
          image: localhost:5001/node:latest
          imagePullPolicy: Always
          ports:
            - name: management
              containerPort: 8800
            - name: https
              containerPort: 8802
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.profile }}
            - name: GRAXON_OTEL_HOST
              value: {{ .Values.otel.host }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: management
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: management
            initialDelaySeconds: 10
            periodSeconds: 10