apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-common
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: graxon
    app.kubernetes.io/component: common
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  actuator-password: {{ .Values.actuator.password | b64enc }}