apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-init
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: graxon
    app.kubernetes.io/component: init