
# =================== Logging Config ===================

#
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

# ====================== Actuator ======================

#
management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c

  # ---------------- OpenTelemetry ---------------- #

  #
  otlp:
    metrics:
      export:
        url: http://${GRAXON_OTEL_HOST:localhost}:4318/v1/metrics
        step: 10s
        enabled: true
    tracing:
      endpoint: http://${GRAXON_OTEL_HOST:localhost}:4317/v1/traces
      transport: grpc
      export:
        enabled: true
    logging:
      endpoint: http://${GRAXON_OTEL_HOST:localhost}:4317/v1/logs
      transport: grpc
      export:
        enabled: true
