apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-notifier
  labels: {{- include "common.labels.notifier" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "common.labels.notifier" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.notifier" . | nindent 8 }}
    spec:
      initContainers:
        - name: wait-for-backends
          image: bitnami/kubectl:1.32.0
          command:
            - /scripts/wait-for-backends.sh
          volumeMounts:
            - name: scripts
              mountPath: /scripts/wait-for-backends.sh
              subPath: wait-for-backends.sh
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: { }
            seccompProfile:
              type: RuntimeDefault
      containers:
      - name: graxon-notifier
        image: localhost:5001/notifier:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8810
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Values.profile }}
        - name: GRAXON_RABBITMQ_HOST
          value: {{ .Release.Name }}-rabbitmq-headless
        - name: GRAXON_OTEL_HOST
          value: {{ .Release.Name }}-otel
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
      serviceAccountName: {{ .Release.Name }}-init
      volumes:
        - name: scripts
          configMap:
            name: {{ .Release.Name }}-scripts
            defaultMode: 0755