apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-notifier
  labels: {{- include "common.labels.notifier" . | nindent 4 }}
    spring-admin: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8810
      targetPort: http
  selector: {{- include "common.labels.notifier" . | nindent 4 }}