apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-notifier
  namespace: {{ .Release.Namespace }}
  labels: {{- include "notifier.labels.default" . | nindent 4 }}
    spring-admin: "true"
spec:
  type: ClusterIP
  ports:
    - name: management
      port: 8800
      targetPort: management
    - name: https
      port: 8810
      targetPort: https
  selector: {{- include "notifier.labels.selector" . | nindent 4 }}