# =================== Server Config ===================

#
server:
  # server port
  port: 8800
  # forward headers to the downstream services
  forward-headers-strategy: framework

# =================== Logging Config ===================

#
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    io.graxon: TRACE

# =================== Spring Config ===================

#
spring:
  application:
    name: core-gateway

  #
  output:
    ansi:
      enabled: always

  #
  threads:
    virtual:
      enabled: true

  #
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.keycloak.svc.cluster.local/realms/Graxon

  # propagate context information (such as tracing or logging context) across reactive operations
  reactor:
    context-propagation: auto

  #
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 5s
        ssl:
          # keystore configuration (for authentication)
          key-store: classpath:keystore.p12
          key-store-password: changeit
          key-store-type: PKCS12
          # truststore configuration (trust all certificates on routes)
          use-insecure-trust-manager: true
      routes:
        # ----------------- Gateway ----------------- #

        #
        - id: core
          filters:
            - BeforeRedirectionFilter
          uri: https://${GRAXON_CORE_HOST:localhost}:8801
          predicates:
            - Path=/api/v1/core/**,/api/v1/projects/**

        #
        - id: notifier
          uri: http://${GRAXON_NOTIFIER_HOST:localhost}:8810
          predicates:
            - Path=/api/v1/notifier/**

        # ----------------- Swagger ----------------- #

        #
        - id: core-service
          uri: https://${GRAXON_CORE_HOST:localhost}:8801
          predicates:
            - Path=/core-service/v3/api-docs

        #
        - id: notifier-service
          uri: http://${GRAXON_NOTIFIER_HOST:localhost}:8810
          predicates:
            - Path=/notifier-service/v3/api-docs

# ================== SpringDoc Config ==================

#
springdoc:
  swagger-ui:
    use-root-path: true
    urls:
      - name: gateway
        url: /v3/api-docs
      - name: core
        url: /core-service/v3/api-docs
      - name: notifier
        url: /notifier-service/v3/api-docs

# ====================== Actuator ======================

#
management:

  # actuator info
  info:
    env:
      enabled: true

  # actuator endpoints exposure
  endpoints:
    web:
      exposure:
        include: "*"

  # actuator health settings
  endpoint:
    health:
      show-details: always
      group:
        custom:
          show-details: always
          show-components: always
      probes:
        enabled: true

  #
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c

  # ---------------- OpenTelemetry ---------------- #

  #
  otlp:
    metrics:
      export:
        url: http://${GRAXON_OTEL_HOST:localhost}:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://${GRAXON_OTEL_HOST:localhost}:4317/v1/traces
      transport: grpc
    logging:
      endpoint: http://${GRAXON_OTEL_HOST:localhost}:4317/v1/logs
      transport: grpc
