apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gateway
  labels: {{- include "common.labels.gateway" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "common.labels.gateway" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.gateway" . | nindent 8 }}
    spec:
      containers:
      - name: graxon-gateway
        image: localhost:5001/gateway:latest
        imagePullPolicy: Always        
        ports:
        - name: http
          containerPort: 8800
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Values.profile }}
        - name: GRAXON_OTEL_HOST
          value: {{ .Release.Name }}-otel
        - name: GRAXON_CORE_HOST
          value: {{ .Release.Name }}-core
        - name: GRAXON_NOTIFIER_HOST
          value: {{ .Release.Name }}-notifier
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10