apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway
  labels: {{- include "common.labels.gateway" . | nindent 4 }}
    spring-admin: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 8800
      targetPort: http
  selector: {{- include "common.labels.gateway" . | nindent 4 }}