apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-graxon-jaeger
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: graxon
    app.kubernetes.io/component: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: graxon
      app.kubernetes.io/component: jaeger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: graxon
        app.kubernetes.io/component: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.64.0
          args:
            - "--memory.max-traces=1000"
          ports:
            - name: ui
              containerPort: 16686
            - name: otlp-grpc
              containerPort: 4317
            - name: otlp-http
              containerPort: 4318
          env:
            - name: OTEL_TRACES_SAMPLER
              value: "always_off"
            - name: JAEGER_REPORTER_MAX_QUEUE_SIZE
              value: "250"
