apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-graxon-jaeger
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: graxon
    app.kubernetes.io/component: jaeger
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: ui
      port: 16686
      targetPort: ui
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: graxon
    app.kubernetes.io/component: jaeger