# =================== Server Config ===================

#
server:
  port: 8820

# =================== Spring Config ===================

#
spring:
  application:
    name: graxon-admin

  #
  output:
    ansi:
      enabled: always

  #
  threads:
    virtual:
      enabled: true

  #
  thymeleaf:
    check-template-location: false

  #
  boot:
    admin:
      ui:
        brand: "Graxon"
        title: "Graxon Admin"
        theme:
          color: "#e344ab"

  #
  cloud:
    kubernetes:
      discovery:

        service-labels:
          spring-admin: "true"

  #
  security:
    user:
      name: "admin"
      password: "password"

