apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-graxon-admin
  labels: {{- include "common.labels.admin" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-graxon-admin
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ .Release.Name }}-graxon-admin
    namespace: {{ .Release.Namespace }}