apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-graxon-prometheus
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: graxon
    app.kubernetes.io/component: prometheus
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  tls:
    - hosts:
        - "prometheus.{{ .Values.ingress.hostname }}"
      secretName: "prometheus.{{ .Values.ingress.hostname }}"
  rules:
    - host: "prometheus.{{ .Values.ingress.hostname }}"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-graxon-prometheus
                port:
                  name: http