apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-core
  namespace: {{ .Release.Namespace }}
  labels: {{- include "core.labels.default" . | nindent 4 }}
    spring-admin: "true"
spec:
  type: ClusterIP
  ports:
    - name: management
      port: 8800
      targetPort: management
    - name: https
      port: 8802
      targetPort: https
  selector: {{- include "core.labels.selector" . | nindent 4 }}
