apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-graxon-core
  labels: {{- include "common.labels.core" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-graxon-core
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ .Release.Name }}-graxon-core
    namespace: {{ .Release.Namespace }}