apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-graxon-core
  labels: {{- include "common.labels.core" . | nindent 4 }}
    spring-admin: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8801
      targetPort: http
  selector: {{- include "common.labels.core" . | nindent 4 }}