apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-graxon-otel
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: graxon
    app.kubernetes.io/component: otel
data:
  otel-config.yml: |

    # data sources: traces, metrics, logs
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318

    #
    processors:
      batch:
      filter/probes:
        error_mode: ignore
        traces:
          span:
            - IsMatch(attributes["http.url"], "/actuator/*")
            - IsMatch(attributes["http.url"], "/v3/api-docs(/*)")
            - IsMatch(attributes["http.url"], "/webjars/*")

    #
    exporters:
      debug:
        verbosity: basic
        use_internal_logger: false
      otlp/jaeger:
        endpoint: {{ .Release.Name }}-graxon-jaeger:4317
        tls:
          insecure: true
      prometheus:
        endpoint: ${env:MY_POD_IP}:9090

    #
    service:
      pipelines:
        traces:
          receivers: [ otlp ]
          processors: [ filter/probes ]
          exporters: [ otlp/jaeger ]
        metrics:
          receivers: [ otlp ]
          exporters: [ prometheus ]
        logs:
          receivers: [ otlp ]
          exporters: [ debug ]
